//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由工具產生。
//     Runtime Version: 4.0.30319.42000
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerBetting.Properties
{
    using System;
    using System.Globalization;
    using System.Resources;

    internal class Resources
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal Resources()
        {
        }

        internal static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    ResourceManager temp = new ResourceManager("PokerBetting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        internal static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }
    }
}
